#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 ...

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.3s

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 199B done
#1 DONE 0.4s

#3 [internal] load metadata for docker.io/library/python:3.10-alpine
#3 ...

#4 [auth] library/python:pull token for registry-1.docker.io
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.10-alpine
#3 DONE 1.6s

#5 [internal] load build context
#5 DONE 0.0s

#6 [1/4] FROM docker.io/library/python:3.10-alpine@sha256:27b5136cf3c1b877dee1ef2be1f9956b196072fa71b5f8d3eef58b05086ffc75
#6 resolve docker.io/library/python:3.10-alpine@sha256:27b5136cf3c1b877dee1ef2be1f9956b196072fa71b5f8d3eef58b05086ffc75
#6 resolve docker.io/library/python:3.10-alpine@sha256:27b5136cf3c1b877dee1ef2be1f9956b196072fa71b5f8d3eef58b05086ffc75 0.2s done
#6 sha256:27b5136cf3c1b877dee1ef2be1f9956b196072fa71b5f8d3eef58b05086ffc75 10.30kB / 10.30kB done
#6 sha256:fe777da3ea4af6625dec5f53a99547c45a7d90bfd5ad1af348244569fb6d2d2b 1.93kB / 1.93kB done
#6 sha256:89b2167400ba4eedcc3d8839396e2a32b61eb3ccf956f78ff2ff9b4188c6b254 6.30kB / 6.30kB done
#6 sha256:2781bbec29c7c89632af77b943bc6138e91539bc79069532581314b11a960a4a 0B / 12.22MB 0.6s
#6 sha256:1717f0165ffa072906ac73c9e4f5e3a3dbee324bfa2f234870f1530bf97b4a5b 0B / 461.80kB 0.7s
#6 ...

#5 [internal] load build context
#5 transferring context: 703.06kB 0.5s done
#5 DONE 1.0s

#6 [1/4] FROM docker.io/library/python:3.10-alpine@sha256:27b5136cf3c1b877dee1ef2be1f9956b196072fa71b5f8d3eef58b05086ffc75
#6 sha256:2781bbec29c7c89632af77b943bc6138e91539bc79069532581314b11a960a4a 1.05MB / 12.22MB 0.8s
#6 extracting sha256:1717f0165ffa072906ac73c9e4f5e3a3dbee324bfa2f234870f1530bf97b4a5b
#6 sha256:2781bbec29c7c89632af77b943bc6138e91539bc79069532581314b11a960a4a 9.44MB / 12.22MB 1.0s
#6 sha256:1717f0165ffa072906ac73c9e4f5e3a3dbee324bfa2f234870f1530bf97b4a5b 461.80kB / 461.80kB 0.9s done
#6 sha256:7e125cf812e71195178cdd9570559dcca866561707e7eef31e45c32ee963ef78 229B / 229B 1.0s done
#6 sha256:e55a234a52774b0ff8d878af7eca2d196dd013cc749ae0fe114d178758269b1f 0B / 3.08MB 1.0s
#6 sha256:2781bbec29c7c89632af77b943bc6138e91539bc79069532581314b11a960a4a 12.22MB / 12.22MB 1.1s
#6 extracting sha256:1717f0165ffa072906ac73c9e4f5e3a3dbee324bfa2f234870f1530bf97b4a5b 0.2s done
#6 sha256:e55a234a52774b0ff8d878af7eca2d196dd013cc749ae0fe114d178758269b1f 1.05MB / 3.08MB 1.1s
#6 sha256:2781bbec29c7c89632af77b943bc6138e91539bc79069532581314b11a960a4a 12.22MB / 12.22MB 1.3s done
#6 sha256:e55a234a52774b0ff8d878af7eca2d196dd013cc749ae0fe114d178758269b1f 3.08MB / 3.08MB 1.3s
#6 sha256:e55a234a52774b0ff8d878af7eca2d196dd013cc749ae0fe114d178758269b1f 3.08MB / 3.08MB 1.4s done
#6 extracting sha256:2781bbec29c7c89632af77b943bc6138e91539bc79069532581314b11a960a4a
#6 extracting sha256:2781bbec29c7c89632af77b943bc6138e91539bc79069532581314b11a960a4a 0.7s done
#6 extracting sha256:7e125cf812e71195178cdd9570559dcca866561707e7eef31e45c32ee963ef78
#6 extracting sha256:7e125cf812e71195178cdd9570559dcca866561707e7eef31e45c32ee963ef78 done
#6 extracting sha256:e55a234a52774b0ff8d878af7eca2d196dd013cc749ae0fe114d178758269b1f
#6 extracting sha256:e55a234a52774b0ff8d878af7eca2d196dd013cc749ae0fe114d178758269b1f 0.3s done
#6 DONE 4.5s

#7 [2/4] COPY . /app
#7 DONE 1.8s

#8 [3/4] WORKDIR /app
#8 DONE 0.3s

#9 [4/4] RUN pip install --upgrade pip && pip install pipenv && pipenv install --dev
#9 3.661 Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (23.0.1)
#9 3.810 Collecting pip
#9 3.854   Downloading pip-24.2-py3-none-any.whl (1.8 MB)
#9 4.031      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 10.5 MB/s eta 0:00:00
#9 4.122 Installing collected packages: pip
#9 4.122   Attempting uninstall: pip
#9 4.123     Found existing installation: pip 23.0.1
#9 4.314     Uninstalling pip-23.0.1:
#9 4.768       Successfully uninstalled pip-23.0.1
#9 6.281 Successfully installed pip-24.2
#9 6.282 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 7.298 Collecting pipenv
#9 7.345   Downloading pipenv-2024.0.1-py3-none-any.whl.metadata (19 kB)
#9 7.464 Collecting certifi (from pipenv)
#9 7.472   Downloading certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
#9 7.921 Collecting setuptools>=67 (from pipenv)
#9 7.930   Downloading setuptools-72.1.0-py3-none-any.whl.metadata (6.6 kB)
#9 8.198 Collecting virtualenv>=20.24.2 (from pipenv)
#9 8.212   Downloading virtualenv-20.26.3-py3-none-any.whl.metadata (4.5 kB)
#9 8.308 Collecting distlib<1,>=0.3.7 (from virtualenv>=20.24.2->pipenv)
#9 8.317   Downloading distlib-0.3.8-py2.py3-none-any.whl.metadata (5.1 kB)
#9 8.447 Collecting filelock<4,>=3.12.2 (from virtualenv>=20.24.2->pipenv)
#9 8.457   Downloading filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)
#9 8.583 Collecting platformdirs<5,>=3.9.1 (from virtualenv>=20.24.2->pipenv)
#9 8.594   Downloading platformdirs-4.2.2-py3-none-any.whl.metadata (11 kB)
#9 8.649 Downloading pipenv-2024.0.1-py3-none-any.whl (3.2 MB)
#9 8.790    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 24.1 MB/s eta 0:00:00
#9 8.804 Downloading setuptools-72.1.0-py3-none-any.whl (2.3 MB)
#9 8.907    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 21.2 MB/s eta 0:00:00
#9 8.920 Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
#9 9.100    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 31.0 MB/s eta 0:00:00
#9 9.110 Downloading certifi-2024.7.4-py3-none-any.whl (162 kB)
#9 9.158 Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#9 9.215 Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#9 9.257 Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#9 9.538 Installing collected packages: distlib, setuptools, platformdirs, filelock, certifi, virtualenv, pipenv
#9 9.700   Attempting uninstall: setuptools
#9 9.701     Found existing installation: setuptools 65.5.1
#9 9.733     Uninstalling setuptools-65.5.1:
#9 9.954       Successfully uninstalled setuptools-65.5.1
#9 14.27 Successfully installed certifi-2024.7.4 distlib-0.3.8 filelock-3.15.4 pipenv-2024.0.1 platformdirs-4.2.2 setuptools-72.1.0 virtualenv-20.26.3
#9 14.27 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#9 15.16 Creating a virtualenv for this project...
#9 15.16 Pipfile: /app/Pipfile
#9 15.18 Using default python from /usr/local/bin/python (3.10.14) to create virtualenv...
#9 15.98 created virtual environment CPython3.10.14.final.0-64 in 486ms
#9 15.98   creator CPython3Posix(dest=/root/.local/share/virtualenvs/app-4PlAip0Q, clear=False, no_vcs_ignore=False, global=False)
#9 15.98   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
#9 15.98     added seed packages: pip==24.1, setuptools==70.1.0, wheel==0.43.0
#9 15.98   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
#9 15.98 
#9 15.98 ✔ Successfully created virtual environment!
#9 16.02 Virtualenv location: /root/.local/share/virtualenvs/app-4PlAip0Q
#9 16.04 To activate this project's virtualenv, run pipenv shell.
#9 16.04 Alternatively, run a command inside the virtualenv with pipenv run.
#9 16.04 To activate this project's virtualenv, run pipenv shell.
#9 16.04 Alternatively, run a command inside the virtualenv with pipenv run.
#9 16.05 Installing dependencies from Pipfile.lock (cbeece)...
#9 27.73 Installing dependencies from Pipfile.lock (cbeece)...
#9 42.36 [pipenv.exceptions.InstallError]: Collecting astroid==2.8.6 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 1))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading astroid-2.8.6-py3-none-any.whl (248 kB)
#9 42.36 [pipenv.exceptions.InstallError]:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.7/248.7 kB 4.2 MB/s eta 0:00:00
#9 42.36 [pipenv.exceptions.InstallError]: Collecting iniconfig==1.1.1 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 2))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
#9 42.36 [pipenv.exceptions.InstallError]: Collecting isort==5.10.1 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 3))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading isort-5.10.1-py3-none-any.whl (103 kB)
#9 42.36 [pipenv.exceptions.InstallError]:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.4/103.4 kB 2.2 MB/s eta 0:00:00
#9 42.36 [pipenv.exceptions.InstallError]: Collecting lazy-object-proxy==1.6.0 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 4))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading lazy-object-proxy-1.6.0.tar.gz (44 kB)
#9 42.36 [pipenv.exceptions.InstallError]:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.5/44.5 kB 406.4 kB/s eta 0:00:00
#9 42.36 [pipenv.exceptions.InstallError]:   Installing build dependencies: started
#9 42.36 [pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
#9 42.36 [pipenv.exceptions.InstallError]:   Getting requirements to build wheel: started
#9 42.36 [pipenv.exceptions.InstallError]:   Getting requirements to build wheel: finished with status 'done'
#9 42.36 [pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): started
#9 42.36 [pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): finished with status 'done'
#9 42.36 [pipenv.exceptions.InstallError]: Collecting mccabe==0.6.1 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 5))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
#9 42.36 [pipenv.exceptions.InstallError]: Collecting packaging==21.3 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 6))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading packaging-21.3-py3-none-any.whl (40 kB)
#9 42.36 [pipenv.exceptions.InstallError]:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 720.6 kB/s eta 0:00:00
#9 42.36 [pipenv.exceptions.InstallError]: Collecting platformdirs==2.4.0 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 7))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading platformdirs-2.4.0-py3-none-any.whl (14 kB)
#9 42.36 [pipenv.exceptions.InstallError]: Collecting pluggy==1.0.0 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 8))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
#9 42.36 [pipenv.exceptions.InstallError]: Collecting py==1.11.0 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 9))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading py-1.11.0-py2.py3-none-any.whl (98 kB)
#9 42.36 [pipenv.exceptions.InstallError]:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 2.7 MB/s eta 0:00:00
#9 42.36 [pipenv.exceptions.InstallError]: Collecting pylint==2.11.1 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 10))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading pylint-2.11.1-py3-none-any.whl (392 kB)
#9 42.36 [pipenv.exceptions.InstallError]:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 392.1/392.1 kB 6.1 MB/s eta 0:00:00
#9 42.36 [pipenv.exceptions.InstallError]: Collecting pyparsing==3.0.6 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 11))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading pyparsing-3.0.6-py3-none-any.whl (97 kB)
#9 42.36 [pipenv.exceptions.InstallError]:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.6/97.6 kB 1.9 MB/s eta 0:00:00
#9 42.36 [pipenv.exceptions.InstallError]: Collecting pytest==6.2.5 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 12))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading pytest-6.2.5-py3-none-any.whl (280 kB)
#9 42.36 [pipenv.exceptions.InstallError]:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.7/280.7 kB 4.1 MB/s eta 0:00:00
#9 42.36 [pipenv.exceptions.InstallError]: Collecting pytest-asyncio==0.16.0 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 13))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading pytest_asyncio-0.16.0-py3-none-any.whl (12 kB)
#9 42.36 [pipenv.exceptions.InstallError]: Collecting pytest-runner==5.3.1 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 14))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading pytest_runner-5.3.1-py3-none-any.whl (7.1 kB)
#9 42.36 [pipenv.exceptions.InstallError]: Collecting pyyaml==6.0 (from -r /tmp/pipenv-yv0bjkqp-requirements/pipenv-imu2szbz-hashed-reqs.txt (line 15))
#9 42.36 [pipenv.exceptions.InstallError]:   Downloading PyYAML-6.0.tar.gz (124 kB)
#9 42.36 [pipenv.exceptions.InstallError]:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 2.9 MB/s eta 0:00:00
#9 42.36 [pipenv.exceptions.InstallError]:   Installing build dependencies: started
#9 42.36 [pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
#9 42.36 [pipenv.exceptions.InstallError]:   Getting requirements to build wheel: started
#9 42.36 [pipenv.exceptions.InstallError]:   Getting requirements to build wheel: finished with status 'error'
#9 42.36 [pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
#9 42.36 [pipenv.exceptions.InstallError]:   
#9 42.36 [pipenv.exceptions.InstallError]:   × Getting requirements to build wheel did not run successfully.
#9 42.36 [pipenv.exceptions.InstallError]:   │ exit code: 1
#9 42.36 [pipenv.exceptions.InstallError]:   ╰─> [48 lines of output]
#9 42.36 [pipenv.exceptions.InstallError]:       running egg_info
#9 42.36 [pipenv.exceptions.InstallError]:       writing lib/PyYAML.egg-info/PKG-INFO
#9 42.36 [pipenv.exceptions.InstallError]:       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
#9 42.36 [pipenv.exceptions.InstallError]:       writing top-level names to lib/PyYAML.egg-info/top_level.txt
#9 42.36 [pipenv.exceptions.InstallError]:       Traceback (most recent call last):
#9 42.36 [pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#9 42.36 [pipenv.exceptions.InstallError]:           main()
#9 42.36 [pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#9 42.36 [pipenv.exceptions.InstallError]:           json_out['return_val'] = hook(**hook_input['kwargs'])
#9 42.36 [pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#9 42.36 [pipenv.exceptions.InstallError]:           return hook(config_settings)
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
#9 42.36 [pipenv.exceptions.InstallError]:           return self._get_build_requires(config_settings, requirements=[])
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
#9 42.36 [pipenv.exceptions.InstallError]:           self.run_setup()
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
#9 42.36 [pipenv.exceptions.InstallError]:           exec(code, locals())
#9 42.36 [pipenv.exceptions.InstallError]:         File "<string>", line 288, in <module>
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
#9 42.36 [pipenv.exceptions.InstallError]:           return distutils.core.setup(**attrs)
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
#9 42.36 [pipenv.exceptions.InstallError]:           return run_commands(dist)
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
#9 42.36 [pipenv.exceptions.InstallError]:           dist.run_commands()
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
#9 42.36 [pipenv.exceptions.InstallError]:           self.run_command(cmd)
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 945, in run_command
#9 42.36 [pipenv.exceptions.InstallError]:           super().run_command(command)
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
#9 42.36 [pipenv.exceptions.InstallError]:           cmd_obj.run()
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 310, in run
#9 42.36 [pipenv.exceptions.InstallError]:           self.find_sources()
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 318, in find_sources
#9 42.36 [pipenv.exceptions.InstallError]:           mm.run()
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 539, in run
#9 42.36 [pipenv.exceptions.InstallError]:           self.add_defaults()
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 577, in add_defaults
#9 42.36 [pipenv.exceptions.InstallError]:           sdist.add_defaults(self)
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
#9 42.36 [pipenv.exceptions.InstallError]:           super().add_defaults()
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
#9 42.36 [pipenv.exceptions.InstallError]:           self._add_defaults_ext()
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
#9 42.36 [pipenv.exceptions.InstallError]:           self.filelist.extend(build_ext.get_source_files())
#9 42.36 [pipenv.exceptions.InstallError]:         File "<string>", line 204, in get_source_files
#9 42.36 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-d8rf5sbz/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
#9 42.36 [pipenv.exceptions.InstallError]:           raise AttributeError(attr)
#9 42.36 [pipenv.exceptions.InstallError]:       AttributeError: cython_sources
#9 42.36 [pipenv.exceptions.InstallError]:       [end of output]
#9 42.36 [pipenv.exceptions.InstallError]:   
#9 42.36 [pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
#9 42.36 [pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
#9 42.36 [pipenv.exceptions.InstallError]: 
#9 42.36 [pipenv.exceptions.InstallError]: × Getting requirements to build wheel did not run successfully.
#9 42.36 [pipenv.exceptions.InstallError]: │ exit code: 1
#9 42.36 [pipenv.exceptions.InstallError]: ╰─> See above for output.
#9 42.36 [pipenv.exceptions.InstallError]: 
#9 42.36 [pipenv.exceptions.InstallError]: note: This error originates from a subprocess, and is likely not a problem with pip.
#9 42.36 ERROR: Couldn't install package: {}
#9 42.36  Package installation failed...
#9 42.37 /usr/local/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 106 is still running
#9 42.37   _warn("subprocess %s is still running" % self.pid,
#9 42.37 ResourceWarning: Enable tracemalloc to get the object allocation traceback
#9 42.37 sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
#9 42.37 ResourceWarning: Enable tracemalloc to get the object allocation traceback
#9 42.37 sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
#9 42.37 ResourceWarning: Enable tracemalloc to get the object allocation traceback
#9 ERROR: process "/bin/sh -c pip install --upgrade pip && pip install pipenv && pipenv install --dev" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --upgrade pip && pip install pipenv && pipenv install --dev:
42.36 [pipenv.exceptions.InstallError]: note: This error originates from a subprocess, and is likely not a problem with pip.
42.36 ERROR: Couldn't install package: {}
42.36  Package installation failed...
42.37 /usr/local/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 106 is still running
42.37   _warn("subprocess %s is still running" % self.pid,
42.37 ResourceWarning: Enable tracemalloc to get the object allocation traceback
42.37 sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
42.37 ResourceWarning: Enable tracemalloc to get the object allocation traceback
42.37 sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
42.37 ResourceWarning: Enable tracemalloc to get the object allocation traceback
------
Dockerfile:6
--------------------
   4 |     WORKDIR /app
   5 |     
   6 | >>> RUN pip install --upgrade pip && pip install pipenv && pipenv install --dev
   7 |     
   8 |     CMD ["pipenv", "run", "pytest"]
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --upgrade pip && pip install pipenv && pipenv install --dev" did not complete successfully: exit code: 1
Duration: 0:54.07